services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner-dev
    environment:
      - DATABASE_URI
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - .:/workspace:cached
      - /etc/localtime:/etc/localtime:ro
  phoenix:
    image:
      arizephoenix/phoenix:latest
    ports:
      - 6006:6006  # PHOENIX_PORT
      - 4317:4317  # PHOENIX_GRPC_PORT
    environment:
      - PHOENIX_WORKING_DIR=/mnt/data
    volumes:
      - phoenix_data:/mnt/data

volumes:
  phoenix_data:

networks:
  default:
    name: app-network
