"""gender type for user

Revision ID: 34896bb52eb1
Revises: 3fa7451682f8
Create Date: 2026-03-02 19:24:27.633778

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '34896bb52eb1'
down_revision: Union[str, None] = '3fa7451682f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.Enum('male', 'female', 'unknown', name='gender'), server_default="unknown", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
